name: aviatortutor
region: nyc

# Backend API Service
services:
  - name: backend
    github:
      repo: Samic333/AV
      branch: main
      deploy_on_push: true
    source_dir: backend
    # Only build, do not migrate here
    build_command: npm ci && npm run build
    run_command: npm run start:prod
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET
      - key: JWT_SECRET
        value: "generate-a-secure-secret-here"
        type: SECRET
      - key: JWT_REFRESH_SECRET
        value: "generate-a-secure-refresh-secret-here"
        type: SECRET
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "30d"
      - key: FRONTEND_URL
        value: ${frontend.PUBLIC_URL}
    routes:
      - path: /api

  - name: frontend
    github:
      repo: Samic333/AV
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /
    envs:
      - key: NODE_ENV
        value: production
      # Use relative path for API since both share the same domain
      - key: NEXT_PUBLIC_API_URL
        value: /api
    routes:
      - path: /

# Database Migration Job (Runs before deployment)
jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: Samic333/AV
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: npm ci && npx prisma generate && npm run build
    run_command: npx prisma migrate deploy
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET

# Managed PostgreSQL Database
databases:
  - name: db
    engine: PG
    version: "15"
    production: true
    cluster_name: aviatortutor-db
